./rtl/control.v
./rtl/correlator.v
./rtl/decode.v
./rtl/detect.v
./rtl/down_converter.v
./rtl/integrator.v
./rtl/local_carry_wave.v
./rtl/m_code_31_generate.v
./rtl/top.v
./tb/tb_top.v
./tb/tb_top_beidou.v
./task3_AI/top_beidou.v
./task3_AI/m_g1_generate.v
./task3_AI/m_g2_generate.v
./task3_AI/ranging_code_generate.v
./task3_AI/integrator_beidou.v
./task3_AI/detect_beidou.v
./task3_AI/control_beidou.v
./task3_AI/decode_beidou.v
